// Compiled by ClojureScript 0.0-2227
goog.provide('tailrecursion.hoplon.app_pages._index_DOT_html');
goog.require('cljs.core');
goog.require('tailrecursion.hoplon.reload');
goog.require('hoplon.jquery.daterangepicker');
goog.require('hoplon.twitter.bootstrap');
goog.require('tailrecursion.javelin');
goog.require('tailrecursion.hoplon');
goog.require('tailrecursion.hoplon');
goog.require('tailrecursion.javelin');
goog.require('hoplon.twitter.bootstrap');
goog.require('hoplon.jquery.daterangepicker');
goog.require('tailrecursion.hoplon.reload');
tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit = (function hoploninit(){tailrecursion.hoplon.reload.reload_all();
tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_ = tailrecursion.javelin.cell(true);
tailrecursion.hoplon.app_pages._index_DOT_html.dates = tailrecursion.javelin.cell(null);
tailrecursion.hoplon.app_pages._index_DOT_html.tab_state = tailrecursion.javelin.cell(0);
tailrecursion.javelin.lift((function (G__9883,G__9884){return (G__9883.cljs$core$IFn$_invoke$arity$2 ? G__9883.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$65,G__9884) : G__9883.call(null,cljs.core.constant$keyword$65,G__9884));
})).call(null,cljs.core.print,tailrecursion.hoplon.app_pages._index_DOT_html.dates);
(tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$66,"en",(tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$41,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$43,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$41,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$43,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 jQuery Date Range Picker") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 jQuery Date Range Picker"))], null);
})()) : tailrecursion.hoplon.html_head.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$41,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$43,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$41,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$43,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 jQuery Date Range Picker") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 jQuery Date Range Picker"))], null);
})())),(tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9886 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Hoplon & jQuery Date Range Picker") : tailrecursion.hoplon.h1.call(null,"Hoplon & jQuery Date Range Picker"));var G__9887 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__9890 = hoplon.twitter.bootstrap.control_label.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),"Date Range"], 0));var G__9892 = hoplon.jquery.daterangepicker.daterange.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$39,tailrecursion.hoplon.app_pages._index_DOT_html.dates,cljs.core.constant$keyword$25,"form-control",cljs.core.constant$keyword$67,"Enter a date range",cljs.core.constant$keyword$38,tailrecursion.javelin.lift(((function (G__9886,G__9887,G__9890){
return (function (G__9901){return new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$68,G__9901], null);
});})(G__9886,G__9887,G__9890))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_)], 0));var G__9891 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),G__9892) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),G__9892));var G__9889 = hoplon.twitter.bootstrap.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$52,tailrecursion.hoplon.app_pages._index_DOT_html.dates,G__9890,G__9891], 0));var G__9898 = (tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$42,"checkbox",cljs.core.constant$keyword$11,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.constant$keyword$69,((function (G__9886,G__9887,G__9890,G__9892,G__9891,G__9889){
return (function (){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.not);
return false;
});})(G__9886,G__9887,G__9890,G__9892,G__9891,G__9889))
) : tailrecursion.hoplon.input.call(null,cljs.core.constant$keyword$42,"checkbox",cljs.core.constant$keyword$11,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.constant$keyword$69,((function (G__9886,G__9887,G__9890,G__9892,G__9891,G__9889){
return (function (){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.not);
return false;
});})(G__9886,G__9887,G__9890,G__9892,G__9891,G__9889))
));var G__9897 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$2(G__9898,"auto-close enabled") : tailrecursion.hoplon.label.call(null,G__9898,"auto-close enabled"));var G__9896 = hoplon.twitter.bootstrap.checkbox.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9897], 0));var G__9894 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),cljs.core.constant$keyword$51,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),G__9896) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),cljs.core.constant$keyword$51,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),G__9896));var G__9893 = hoplon.twitter.bootstrap.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9894], 0));var G__9888 = hoplon.twitter.bootstrap.form_horizontal.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9889,G__9893], 0));var G__9895 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__9900 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$43,"https://github.com/tailrecursion/hoplon-demos/blob/master/jquery-date-picker/src/index.cljs.hl","source code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$43,"https://github.com/tailrecursion/hoplon-demos/blob/master/jquery-date-picker/src/index.cljs.hl","source code"));var G__9899 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$70,"center"], null),G__9900) : tailrecursion.hoplon.p.call(null,cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$70,"center"], null),G__9900));var G__9885 = hoplon.twitter.bootstrap.container.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9886,G__9887,G__9888,G__9895,G__9899], 0));return G__9885;
})()) : tailrecursion.hoplon.html_body.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9886 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Hoplon & jQuery Date Range Picker") : tailrecursion.hoplon.h1.call(null,"Hoplon & jQuery Date Range Picker"));var G__9887 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__9890 = hoplon.twitter.bootstrap.control_label.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),"Date Range"], 0));var G__9892 = hoplon.jquery.daterangepicker.daterange.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$39,tailrecursion.hoplon.app_pages._index_DOT_html.dates,cljs.core.constant$keyword$25,"form-control",cljs.core.constant$keyword$67,"Enter a date range",cljs.core.constant$keyword$38,tailrecursion.javelin.lift(((function (G__9886,G__9887,G__9890){
return (function (G__9901){return new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$68,G__9901], null);
});})(G__9886,G__9887,G__9890))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_)], 0));var G__9891 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),G__9892) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),G__9892));var G__9889 = hoplon.twitter.bootstrap.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$52,tailrecursion.hoplon.app_pages._index_DOT_html.dates,G__9890,G__9891], 0));var G__9898 = (tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$42,"checkbox",cljs.core.constant$keyword$11,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.constant$keyword$69,((function (G__9886,G__9887,G__9890,G__9892,G__9891,G__9889){
return (function (){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.not);
return false;
});})(G__9886,G__9887,G__9890,G__9892,G__9891,G__9889))
) : tailrecursion.hoplon.input.call(null,cljs.core.constant$keyword$42,"checkbox",cljs.core.constant$keyword$11,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.constant$keyword$69,((function (G__9886,G__9887,G__9890,G__9892,G__9891,G__9889){
return (function (){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.not);
return false;
});})(G__9886,G__9887,G__9890,G__9892,G__9891,G__9889))
));var G__9897 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$2(G__9898,"auto-close enabled") : tailrecursion.hoplon.label.call(null,G__9898,"auto-close enabled"));var G__9896 = hoplon.twitter.bootstrap.checkbox.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9897], 0));var G__9894 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),cljs.core.constant$keyword$51,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),G__9896) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),cljs.core.constant$keyword$51,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),G__9896));var G__9893 = hoplon.twitter.bootstrap.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9894], 0));var G__9888 = hoplon.twitter.bootstrap.form_horizontal.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9889,G__9893], 0));var G__9895 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__9900 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$43,"https://github.com/tailrecursion/hoplon-demos/blob/master/jquery-date-picker/src/index.cljs.hl","source code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$43,"https://github.com/tailrecursion/hoplon-demos/blob/master/jquery-date-picker/src/index.cljs.hl","source code"));var G__9899 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$70,"center"], null),G__9900) : tailrecursion.hoplon.p.call(null,cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$70,"center"], null),G__9900));var G__9885 = hoplon.twitter.bootstrap.container.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9886,G__9887,G__9888,G__9895,G__9899], 0));return G__9885;
})()))) : tailrecursion.hoplon.html.call(null,cljs.core.constant$keyword$66,"en",(tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$41,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$43,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$41,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$43,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 jQuery Date Range Picker") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 jQuery Date Range Picker"))], null);
})()) : tailrecursion.hoplon.html_head.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$41,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$43,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$41,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$43,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 jQuery Date Range Picker") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 jQuery Date Range Picker"))], null);
})())),(tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9886 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Hoplon & jQuery Date Range Picker") : tailrecursion.hoplon.h1.call(null,"Hoplon & jQuery Date Range Picker"));var G__9887 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__9890 = hoplon.twitter.bootstrap.control_label.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),"Date Range"], 0));var G__9892 = hoplon.jquery.daterangepicker.daterange.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$39,tailrecursion.hoplon.app_pages._index_DOT_html.dates,cljs.core.constant$keyword$25,"form-control",cljs.core.constant$keyword$67,"Enter a date range",cljs.core.constant$keyword$38,tailrecursion.javelin.lift(((function (G__9886,G__9887,G__9890){
return (function (G__9901){return new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$68,G__9901], null);
});})(G__9886,G__9887,G__9890))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_)], 0));var G__9891 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),G__9892) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),G__9892));var G__9889 = hoplon.twitter.bootstrap.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$52,tailrecursion.hoplon.app_pages._index_DOT_html.dates,G__9890,G__9891], 0));var G__9898 = (tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$42,"checkbox",cljs.core.constant$keyword$11,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.constant$keyword$69,((function (G__9886,G__9887,G__9890,G__9892,G__9891,G__9889){
return (function (){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.not);
return false;
});})(G__9886,G__9887,G__9890,G__9892,G__9891,G__9889))
) : tailrecursion.hoplon.input.call(null,cljs.core.constant$keyword$42,"checkbox",cljs.core.constant$keyword$11,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.constant$keyword$69,((function (G__9886,G__9887,G__9890,G__9892,G__9891,G__9889){
return (function (){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.not);
return false;
});})(G__9886,G__9887,G__9890,G__9892,G__9891,G__9889))
));var G__9897 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$2(G__9898,"auto-close enabled") : tailrecursion.hoplon.label.call(null,G__9898,"auto-close enabled"));var G__9896 = hoplon.twitter.bootstrap.checkbox.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9897], 0));var G__9894 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),cljs.core.constant$keyword$51,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),G__9896) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),cljs.core.constant$keyword$51,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),G__9896));var G__9893 = hoplon.twitter.bootstrap.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9894], 0));var G__9888 = hoplon.twitter.bootstrap.form_horizontal.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9889,G__9893], 0));var G__9895 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__9900 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$43,"https://github.com/tailrecursion/hoplon-demos/blob/master/jquery-date-picker/src/index.cljs.hl","source code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$43,"https://github.com/tailrecursion/hoplon-demos/blob/master/jquery-date-picker/src/index.cljs.hl","source code"));var G__9899 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$70,"center"], null),G__9900) : tailrecursion.hoplon.p.call(null,cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$70,"center"], null),G__9900));var G__9885 = hoplon.twitter.bootstrap.container.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9886,G__9887,G__9888,G__9895,G__9899], 0));return G__9885;
})()) : tailrecursion.hoplon.html_body.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9886 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Hoplon & jQuery Date Range Picker") : tailrecursion.hoplon.h1.call(null,"Hoplon & jQuery Date Range Picker"));var G__9887 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__9890 = hoplon.twitter.bootstrap.control_label.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),"Date Range"], 0));var G__9892 = hoplon.jquery.daterangepicker.daterange.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$39,tailrecursion.hoplon.app_pages._index_DOT_html.dates,cljs.core.constant$keyword$25,"form-control",cljs.core.constant$keyword$67,"Enter a date range",cljs.core.constant$keyword$38,tailrecursion.javelin.lift(((function (G__9886,G__9887,G__9890){
return (function (G__9901){return new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$68,G__9901], null);
});})(G__9886,G__9887,G__9890))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_)], 0));var G__9891 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),G__9892) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),G__9892));var G__9889 = hoplon.twitter.bootstrap.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$52,tailrecursion.hoplon.app_pages._index_DOT_html.dates,G__9890,G__9891], 0));var G__9898 = (tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$42,"checkbox",cljs.core.constant$keyword$11,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.constant$keyword$69,((function (G__9886,G__9887,G__9890,G__9892,G__9891,G__9889){
return (function (){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.not);
return false;
});})(G__9886,G__9887,G__9890,G__9892,G__9891,G__9889))
) : tailrecursion.hoplon.input.call(null,cljs.core.constant$keyword$42,"checkbox",cljs.core.constant$keyword$11,tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.constant$keyword$69,((function (G__9886,G__9887,G__9890,G__9892,G__9891,G__9889){
return (function (){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.close_QMARK_,cljs.core.not);
return false;
});})(G__9886,G__9887,G__9890,G__9892,G__9891,G__9889))
));var G__9897 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$2(G__9898,"auto-close enabled") : tailrecursion.hoplon.label.call(null,G__9898,"auto-close enabled"));var G__9896 = hoplon.twitter.bootstrap.checkbox.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9897], 0));var G__9894 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),cljs.core.constant$keyword$51,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),G__9896) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$48,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,10], null),cljs.core.constant$keyword$51,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$45,2], null),G__9896));var G__9893 = hoplon.twitter.bootstrap.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9894], 0));var G__9888 = hoplon.twitter.bootstrap.form_horizontal.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9889,G__9893], 0));var G__9895 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__9900 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$43,"https://github.com/tailrecursion/hoplon-demos/blob/master/jquery-date-picker/src/index.cljs.hl","source code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$43,"https://github.com/tailrecursion/hoplon-demos/blob/master/jquery-date-picker/src/index.cljs.hl","source code"));var G__9899 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$70,"center"], null),G__9900) : tailrecursion.hoplon.p.call(null,cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$70,"center"], null),G__9900));var G__9885 = hoplon.twitter.bootstrap.container.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__9886,G__9887,G__9888,G__9895,G__9899], 0));return G__9885;
})()))));
return tailrecursion.hoplon.init();
});
goog.exportSymbol('tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit', tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit);
