// Compiled by ClojureScript 0.0-2227
goog.provide('tailrecursion.hoplon.app_pages._index_DOT_html');
goog.require('cljs.core');
goog.require('tailrecursion.javelin');
goog.require('tailrecursion.hoplon');
goog.require('tailrecursion.hoplon');
goog.require('tailrecursion.javelin');
goog.require('flickr');
tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit = (function hoploninit(){/**
* Flickr search API queries, will be chosen randomly and submitted to obtain
* interesting images which will be displayed in the scrolling div.
*/
tailrecursion.hoplon.app_pages._index_DOT_html.queries = cljs.core.PersistentVector.fromArray(["wtf","meme","happy","jewels","farming","flamenco","omg","blue","green","castles","goodbye","spaghetti","sad","love","space","haircut","amazing","hilarious","red","hate","tango","tractor","awesome","submarines","nyc","nasa","ships","hunting","alabama","motorcycles","hey","fool","funny","sailing","bananas","underground"], true);
/**
* The current list of image urls.
*/
tailrecursion.hoplon.app_pages._index_DOT_html.state = tailrecursion.javelin.cell(cljs.core.PersistentVector.EMPTY);
/**
* The last XHR error.
*/
tailrecursion.hoplon.app_pages._index_DOT_html.error = tailrecursion.javelin.cell(null);
/**
* A vector of in-progress async calls.
*/
tailrecursion.hoplon.app_pages._index_DOT_html.loading = tailrecursion.javelin.cell(cljs.core.PersistentVector.EMPTY);
/**
* True if there are in-progress async calls.
*/
tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_ = tailrecursion.javelin.lift((function (G__9560,G__9561){return (G__9560.cljs$core$IFn$_invoke$arity$1 ? G__9560.cljs$core$IFn$_invoke$arity$1(G__9561) : G__9560.call(null,G__9561));
})).call(null,cljs.core.seq,tailrecursion.hoplon.app_pages._index_DOT_html.loading);
/**
* Fetch some images from the Flickr API and append them to the state cell.
*/
tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_ = (function fetch_images_BANG_(){if(cljs.core.truth_(cljs.core.deref(tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_)))
{return null;
} else
{cljs.core.reset_BANG_(tailrecursion.hoplon.app_pages._index_DOT_html.error,null);
cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$3(tailrecursion.hoplon.app_pages._index_DOT_html.loading,cljs.core.conj,cljs.core.constant$keyword$52);
var q = cljs.core.rand_nth(tailrecursion.hoplon.app_pages._index_DOT_html.queries);return flickr.image_search(q,((function (q){
return (function (p1__6558_SHARP_){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.loading,cljs.core.pop);
return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$3(tailrecursion.hoplon.app_pages._index_DOT_html.state,cljs.core.into,p1__6558_SHARP_);
});})(q))
,((function (q){
return (function (){cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.loading,cljs.core.pop);
return cljs.core.reset_BANG_(tailrecursion.hoplon.app_pages._index_DOT_html.error,cljs.core.constant$keyword$53);
});})(q))
);
}
});
tailrecursion.hoplon.on_BANG_.cljs$core$IMultiFn$_add_method$arity$3(null,cljs.core.constant$keyword$54,(function (elem,_,callback){return (tailrecursion.hoplon.on_BANG_.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.on_BANG_.cljs$core$IFn$_invoke$arity$3(elem,cljs.core.constant$keyword$55,(function (p1__6559_SHARP_){var el = p1__6559_SHARP_.target;var ch = el.clientHeight;var sh = el.scrollHeight;var st = el.scrollTop;var at_end_QMARK_ = cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(ch,(sh - st));if(at_end_QMARK_)
{return (callback.cljs$core$IFn$_invoke$arity$1 ? callback.cljs$core$IFn$_invoke$arity$1(p1__6559_SHARP_) : callback.call(null,p1__6559_SHARP_));
} else
{return null;
}
})) : tailrecursion.hoplon.on_BANG_.call(null,elem,cljs.core.constant$keyword$55,(function (p1__6559_SHARP_){var el = p1__6559_SHARP_.target;var ch = el.clientHeight;var sh = el.scrollHeight;var st = el.scrollTop;var at_end_QMARK_ = cljs.core._EQ_.cljs$core$IFn$_invoke$arity$2(ch,(sh - st));if(at_end_QMARK_)
{return (callback.cljs$core$IFn$_invoke$arity$1 ? callback.cljs$core$IFn$_invoke$arity$1(p1__6559_SHARP_) : callback.call(null,p1__6559_SHARP_));
} else
{return null;
}
})));
}));
tailrecursion.hoplon.add_initfn_BANG_((function (){return tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_();
}));
(tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$56,"en",(tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,(window["_hoplon_main_css"]))),(meta.cljs$core$IFn$_invoke$arity$2 ? meta.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$60,"utf-8") : meta.call(null,cljs.core.constant$keyword$60,"utf-8")),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Infinite Scroll Demo") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Infinite Scroll Demo")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,"css/main.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,"css/main.css"))], null);
})()) : tailrecursion.hoplon.html_head.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,(window["_hoplon_main_css"]))),(meta.cljs$core$IFn$_invoke$arity$2 ? meta.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$60,"utf-8") : meta.call(null,cljs.core.constant$keyword$60,"utf-8")),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Infinite Scroll Demo") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Infinite Scroll Demo")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,"css/main.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,"css/main.css"))], null);
})())),(tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9563 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Infinite Scrolling") : tailrecursion.hoplon.h1.call(null,"Infinite Scrolling"));var G__9564 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1("Scroll down to see more images...") : tailrecursion.hoplon.p.call(null,"Scroll down to see more images..."));var G__9566 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"loading",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_,"LOADING IMAGES...") : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"loading",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_,"LOADING IMAGES..."));var G__9569 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,"javascript:void(0)",cljs.core.constant$keyword$62,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,"try again") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,"javascript:void(0)",cljs.core.constant$keyword$62,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,"try again"));var G__9567 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$61,"error",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.error,"Error fetching images: ",G__9569) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"error",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.error,"Error fetching images: ",G__9569));var G__9568 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"scroll",cljs.core.constant$keyword$54,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,tailrecursion.hoplon.loop_tpl_STAR_(tailrecursion.hoplon.app_pages._index_DOT_html.state,null,((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (item__8500__auto__){var vec__9572 = tailrecursion.javelin.cell_map(cljs.core.identity,tailrecursion.javelin.lift(((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (G__9574){var map__9573 = G__9574;var map__9573__$1 = ((cljs.core.seq_QMARK_(map__9573))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9573):map__9573);var image = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$50);var link = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$47);return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [link,image], null);
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
).call(null,item__8500__auto__));var link = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,0,null);var image = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,1,null);return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1((tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))) : tailrecursion.hoplon.div.call(null,(tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))));
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
)) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"scroll",cljs.core.constant$keyword$54,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,tailrecursion.hoplon.loop_tpl_STAR_(tailrecursion.hoplon.app_pages._index_DOT_html.state,null,((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (item__8500__auto__){var vec__9572 = tailrecursion.javelin.cell_map(cljs.core.identity,tailrecursion.javelin.lift(((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (G__9574){var map__9573 = G__9574;var map__9573__$1 = ((cljs.core.seq_QMARK_(map__9573))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9573):map__9573);var image = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$50);var link = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$47);return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [link,image], null);
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
).call(null,item__8500__auto__));var link = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,0,null);var image = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,1,null);return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1((tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))) : tailrecursion.hoplon.div.call(null,(tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))));
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
)));var G__9571 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$59,"https://github.com/tailrecursion/hoplon-demos/tree/master/infinite-scroll/src/index.cljs.hl","Source Code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,"https://github.com/tailrecursion/hoplon-demos/tree/master/infinite-scroll/src/index.cljs.hl","Source Code"));var G__9570 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1(G__9571) : tailrecursion.hoplon.p.call(null,G__9571));var G__9565 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$61,"wrapper",G__9566,G__9567,G__9568,G__9570) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"wrapper",G__9566,G__9567,G__9568,G__9570));var G__9562 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"container",G__9563,G__9564,G__9565) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"container",G__9563,G__9564,G__9565));return G__9562;
})()) : tailrecursion.hoplon.html_body.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9563 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Infinite Scrolling") : tailrecursion.hoplon.h1.call(null,"Infinite Scrolling"));var G__9564 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1("Scroll down to see more images...") : tailrecursion.hoplon.p.call(null,"Scroll down to see more images..."));var G__9566 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"loading",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_,"LOADING IMAGES...") : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"loading",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_,"LOADING IMAGES..."));var G__9569 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,"javascript:void(0)",cljs.core.constant$keyword$62,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,"try again") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,"javascript:void(0)",cljs.core.constant$keyword$62,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,"try again"));var G__9567 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$61,"error",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.error,"Error fetching images: ",G__9569) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"error",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.error,"Error fetching images: ",G__9569));var G__9568 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"scroll",cljs.core.constant$keyword$54,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,tailrecursion.hoplon.loop_tpl_STAR_(tailrecursion.hoplon.app_pages._index_DOT_html.state,null,((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (item__8500__auto__){var vec__9572 = tailrecursion.javelin.cell_map(cljs.core.identity,tailrecursion.javelin.lift(((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (G__9574){var map__9573 = G__9574;var map__9573__$1 = ((cljs.core.seq_QMARK_(map__9573))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9573):map__9573);var image = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$50);var link = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$47);return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [link,image], null);
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
).call(null,item__8500__auto__));var link = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,0,null);var image = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,1,null);return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1((tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))) : tailrecursion.hoplon.div.call(null,(tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))));
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
)) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"scroll",cljs.core.constant$keyword$54,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,tailrecursion.hoplon.loop_tpl_STAR_(tailrecursion.hoplon.app_pages._index_DOT_html.state,null,((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (item__8500__auto__){var vec__9572 = tailrecursion.javelin.cell_map(cljs.core.identity,tailrecursion.javelin.lift(((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (G__9574){var map__9573 = G__9574;var map__9573__$1 = ((cljs.core.seq_QMARK_(map__9573))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9573):map__9573);var image = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$50);var link = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$47);return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [link,image], null);
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
).call(null,item__8500__auto__));var link = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,0,null);var image = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,1,null);return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1((tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))) : tailrecursion.hoplon.div.call(null,(tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))));
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
)));var G__9571 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$59,"https://github.com/tailrecursion/hoplon-demos/tree/master/infinite-scroll/src/index.cljs.hl","Source Code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,"https://github.com/tailrecursion/hoplon-demos/tree/master/infinite-scroll/src/index.cljs.hl","Source Code"));var G__9570 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1(G__9571) : tailrecursion.hoplon.p.call(null,G__9571));var G__9565 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$61,"wrapper",G__9566,G__9567,G__9568,G__9570) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"wrapper",G__9566,G__9567,G__9568,G__9570));var G__9562 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"container",G__9563,G__9564,G__9565) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"container",G__9563,G__9564,G__9565));return G__9562;
})()))) : tailrecursion.hoplon.html.call(null,cljs.core.constant$keyword$56,"en",(tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,(window["_hoplon_main_css"]))),(meta.cljs$core$IFn$_invoke$arity$2 ? meta.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$60,"utf-8") : meta.call(null,cljs.core.constant$keyword$60,"utf-8")),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Infinite Scroll Demo") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Infinite Scroll Demo")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,"css/main.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,"css/main.css"))], null);
})()) : tailrecursion.hoplon.html_head.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,(window["_hoplon_main_css"]))),(meta.cljs$core$IFn$_invoke$arity$2 ? meta.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$60,"utf-8") : meta.call(null,cljs.core.constant$keyword$60,"utf-8")),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Infinite Scroll Demo") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Infinite Scroll Demo")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,"css/main.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$57,"stylesheet",cljs.core.constant$keyword$58,"text/css",cljs.core.constant$keyword$59,"css/main.css"))], null);
})())),(tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9563 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Infinite Scrolling") : tailrecursion.hoplon.h1.call(null,"Infinite Scrolling"));var G__9564 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1("Scroll down to see more images...") : tailrecursion.hoplon.p.call(null,"Scroll down to see more images..."));var G__9566 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"loading",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_,"LOADING IMAGES...") : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"loading",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_,"LOADING IMAGES..."));var G__9569 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,"javascript:void(0)",cljs.core.constant$keyword$62,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,"try again") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,"javascript:void(0)",cljs.core.constant$keyword$62,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,"try again"));var G__9567 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$61,"error",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.error,"Error fetching images: ",G__9569) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"error",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.error,"Error fetching images: ",G__9569));var G__9568 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"scroll",cljs.core.constant$keyword$54,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,tailrecursion.hoplon.loop_tpl_STAR_(tailrecursion.hoplon.app_pages._index_DOT_html.state,null,((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (item__8500__auto__){var vec__9572 = tailrecursion.javelin.cell_map(cljs.core.identity,tailrecursion.javelin.lift(((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (G__9574){var map__9573 = G__9574;var map__9573__$1 = ((cljs.core.seq_QMARK_(map__9573))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9573):map__9573);var image = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$50);var link = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$47);return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [link,image], null);
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
).call(null,item__8500__auto__));var link = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,0,null);var image = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,1,null);return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1((tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))) : tailrecursion.hoplon.div.call(null,(tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))));
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
)) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"scroll",cljs.core.constant$keyword$54,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,tailrecursion.hoplon.loop_tpl_STAR_(tailrecursion.hoplon.app_pages._index_DOT_html.state,null,((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (item__8500__auto__){var vec__9572 = tailrecursion.javelin.cell_map(cljs.core.identity,tailrecursion.javelin.lift(((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (G__9574){var map__9573 = G__9574;var map__9573__$1 = ((cljs.core.seq_QMARK_(map__9573))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9573):map__9573);var image = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$50);var link = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$47);return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [link,image], null);
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
).call(null,item__8500__auto__));var link = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,0,null);var image = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,1,null);return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1((tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))) : tailrecursion.hoplon.div.call(null,(tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))));
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
)));var G__9571 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$59,"https://github.com/tailrecursion/hoplon-demos/tree/master/infinite-scroll/src/index.cljs.hl","Source Code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,"https://github.com/tailrecursion/hoplon-demos/tree/master/infinite-scroll/src/index.cljs.hl","Source Code"));var G__9570 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1(G__9571) : tailrecursion.hoplon.p.call(null,G__9571));var G__9565 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$61,"wrapper",G__9566,G__9567,G__9568,G__9570) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"wrapper",G__9566,G__9567,G__9568,G__9570));var G__9562 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"container",G__9563,G__9564,G__9565) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"container",G__9563,G__9564,G__9565));return G__9562;
})()) : tailrecursion.hoplon.html_body.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9563 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Infinite Scrolling") : tailrecursion.hoplon.h1.call(null,"Infinite Scrolling"));var G__9564 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1("Scroll down to see more images...") : tailrecursion.hoplon.p.call(null,"Scroll down to see more images..."));var G__9566 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"loading",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_,"LOADING IMAGES...") : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"loading",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.loading_QMARK_,"LOADING IMAGES..."));var G__9569 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,"javascript:void(0)",cljs.core.constant$keyword$62,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,"try again") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,"javascript:void(0)",cljs.core.constant$keyword$62,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,"try again"));var G__9567 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$61,"error",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.error,"Error fetching images: ",G__9569) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"error",cljs.core.constant$keyword$27,tailrecursion.hoplon.app_pages._index_DOT_html.error,"Error fetching images: ",G__9569));var G__9568 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"scroll",cljs.core.constant$keyword$54,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,tailrecursion.hoplon.loop_tpl_STAR_(tailrecursion.hoplon.app_pages._index_DOT_html.state,null,((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (item__8500__auto__){var vec__9572 = tailrecursion.javelin.cell_map(cljs.core.identity,tailrecursion.javelin.lift(((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (G__9574){var map__9573 = G__9574;var map__9573__$1 = ((cljs.core.seq_QMARK_(map__9573))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9573):map__9573);var image = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$50);var link = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$47);return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [link,image], null);
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
).call(null,item__8500__auto__));var link = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,0,null);var image = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,1,null);return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1((tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))) : tailrecursion.hoplon.div.call(null,(tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))));
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
)) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"scroll",cljs.core.constant$keyword$54,tailrecursion.hoplon.app_pages._index_DOT_html.fetch_images_BANG_,tailrecursion.hoplon.loop_tpl_STAR_(tailrecursion.hoplon.app_pages._index_DOT_html.state,null,((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (item__8500__auto__){var vec__9572 = tailrecursion.javelin.cell_map(cljs.core.identity,tailrecursion.javelin.lift(((function (G__9563,G__9564,G__9566,G__9569,G__9567){
return (function (G__9574){var map__9573 = G__9574;var map__9573__$1 = ((cljs.core.seq_QMARK_(map__9573))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9573):map__9573);var image = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$50);var link = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9573__$1,cljs.core.constant$keyword$47);return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [link,image], null);
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
).call(null,item__8500__auto__));var link = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,0,null);var image = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9572,1,null);return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$1((tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))) : tailrecursion.hoplon.div.call(null,(tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))) : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,link,cljs.core.constant$keyword$63,"_blank",(tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.img.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$64,image) : tailrecursion.hoplon.img.call(null,cljs.core.constant$keyword$64,image))))));
});})(G__9563,G__9564,G__9566,G__9569,G__9567))
)));var G__9571 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$59,"https://github.com/tailrecursion/hoplon-demos/tree/master/infinite-scroll/src/index.cljs.hl","Source Code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$59,"https://github.com/tailrecursion/hoplon-demos/tree/master/infinite-scroll/src/index.cljs.hl","Source Code"));var G__9570 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1(G__9571) : tailrecursion.hoplon.p.call(null,G__9571));var G__9565 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$61,"wrapper",G__9566,G__9567,G__9568,G__9570) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"wrapper",G__9566,G__9567,G__9568,G__9570));var G__9562 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$61,"container",G__9563,G__9564,G__9565) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$61,"container",G__9563,G__9564,G__9565));return G__9562;
})()))));
return tailrecursion.hoplon.init();
});
goog.exportSymbol('tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit', tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit);
