// Compiled by ClojureScript 0.0-2227
goog.provide('tailrecursion.hoplon.svg');
goog.require('cljs.core');
tailrecursion.hoplon.svg.make_svg_ctor = (function make_svg_ctor(tag){var xmlns = "http://www.w3.org/2000/svg";return ((function (xmlns){
return (function() { 
var G__11245__delegate = function (args){return cljs.core.apply.cljs$core$IFn$_invoke$arity$2(document.createElementNS(xmlns,tag),args);
};
var G__11245 = function (var_args){
var args = null;if (arguments.length > 0) {
  args = cljs.core.array_seq(Array.prototype.slice.call(arguments, 0),0);} 
return G__11245__delegate.call(this,args);};
G__11245.cljs$lang$maxFixedArity = 0;
G__11245.cljs$lang$applyTo = (function (arglist__11246){
var args = cljs.core.seq(arglist__11246);
return G__11245__delegate(args);
});
G__11245.cljs$core$IFn$_invoke$arity$variadic = G__11245__delegate;
return G__11245;
})()
;
;})(xmlns))
});
tailrecursion.hoplon.svg.a = tailrecursion.hoplon.svg.make_svg_ctor("svg:a");
tailrecursion.hoplon.svg.altGlyph = tailrecursion.hoplon.svg.make_svg_ctor("svg:altGlyph");
tailrecursion.hoplon.svg.altGlyphDef = tailrecursion.hoplon.svg.make_svg_ctor("svg:altGlyphDef");
tailrecursion.hoplon.svg.altGlyphItem = tailrecursion.hoplon.svg.make_svg_ctor("svg:altGlyphItem");
tailrecursion.hoplon.svg.animate = tailrecursion.hoplon.svg.make_svg_ctor("svg:animate");
tailrecursion.hoplon.svg.animateColor = tailrecursion.hoplon.svg.make_svg_ctor("svg:animateColor");
tailrecursion.hoplon.svg.animateMotion = tailrecursion.hoplon.svg.make_svg_ctor("svg:animateMotion");
tailrecursion.hoplon.svg.animateTransform = tailrecursion.hoplon.svg.make_svg_ctor("svg:animateTransform");
tailrecursion.hoplon.svg.circle = tailrecursion.hoplon.svg.make_svg_ctor("svg:circle");
tailrecursion.hoplon.svg.clipPath = tailrecursion.hoplon.svg.make_svg_ctor("svg:clipPath");
tailrecursion.hoplon.svg.color_profile = tailrecursion.hoplon.svg.make_svg_ctor("svg:color-profile");
tailrecursion.hoplon.svg.cursor = tailrecursion.hoplon.svg.make_svg_ctor("svg:cursor");
tailrecursion.hoplon.svg.defs = tailrecursion.hoplon.svg.make_svg_ctor("svg:defs");
tailrecursion.hoplon.svg.desc = tailrecursion.hoplon.svg.make_svg_ctor("svg:desc");
tailrecursion.hoplon.svg.ellipse = tailrecursion.hoplon.svg.make_svg_ctor("svg:ellipse");
tailrecursion.hoplon.svg.feBlend = tailrecursion.hoplon.svg.make_svg_ctor("svg:feBlend");
tailrecursion.hoplon.svg.feColorMatrix = tailrecursion.hoplon.svg.make_svg_ctor("svg:feColorMatrix");
tailrecursion.hoplon.svg.feComponentTransfer = tailrecursion.hoplon.svg.make_svg_ctor("svg:feComponentTransfer");
tailrecursion.hoplon.svg.feComposite = tailrecursion.hoplon.svg.make_svg_ctor("svg:feComposite");
tailrecursion.hoplon.svg.feConvolveMatrix = tailrecursion.hoplon.svg.make_svg_ctor("svg:feConvolveMatrix");
tailrecursion.hoplon.svg.feDiffuseLighting = tailrecursion.hoplon.svg.make_svg_ctor("svg:feDiffuseLighting");
tailrecursion.hoplon.svg.feDisplacementMap = tailrecursion.hoplon.svg.make_svg_ctor("svg:feDisplacementMap");
tailrecursion.hoplon.svg.feDistantLight = tailrecursion.hoplon.svg.make_svg_ctor("svg:feDistantLight");
tailrecursion.hoplon.svg.feFlood = tailrecursion.hoplon.svg.make_svg_ctor("svg:feFlood");
tailrecursion.hoplon.svg.feFuncA = tailrecursion.hoplon.svg.make_svg_ctor("svg:feFuncA");
tailrecursion.hoplon.svg.feFuncB = tailrecursion.hoplon.svg.make_svg_ctor("svg:feFuncB");
tailrecursion.hoplon.svg.feFuncG = tailrecursion.hoplon.svg.make_svg_ctor("svg:feFuncG");
tailrecursion.hoplon.svg.feFuncR = tailrecursion.hoplon.svg.make_svg_ctor("svg:feFuncR");
tailrecursion.hoplon.svg.feGaussianBlur = tailrecursion.hoplon.svg.make_svg_ctor("svg:feGaussianBlur");
tailrecursion.hoplon.svg.feImage = tailrecursion.hoplon.svg.make_svg_ctor("svg:feImage");
tailrecursion.hoplon.svg.feMerge = tailrecursion.hoplon.svg.make_svg_ctor("svg:feMerge");
tailrecursion.hoplon.svg.feMergeNode = tailrecursion.hoplon.svg.make_svg_ctor("svg:feMergeNode");
tailrecursion.hoplon.svg.feMorphology = tailrecursion.hoplon.svg.make_svg_ctor("svg:feMorphology");
tailrecursion.hoplon.svg.feOffset = tailrecursion.hoplon.svg.make_svg_ctor("svg:feOffset");
tailrecursion.hoplon.svg.fePointLight = tailrecursion.hoplon.svg.make_svg_ctor("svg:fePointLight");
tailrecursion.hoplon.svg.feSpecularLighting = tailrecursion.hoplon.svg.make_svg_ctor("svg:feSpecularLighting");
tailrecursion.hoplon.svg.feSpotLight = tailrecursion.hoplon.svg.make_svg_ctor("svg:feSpotLight");
tailrecursion.hoplon.svg.feTile = tailrecursion.hoplon.svg.make_svg_ctor("svg:feTile");
tailrecursion.hoplon.svg.feTurbulence = tailrecursion.hoplon.svg.make_svg_ctor("svg:feTurbulence");
tailrecursion.hoplon.svg.filter = tailrecursion.hoplon.svg.make_svg_ctor("svg:filter");
tailrecursion.hoplon.svg.font = tailrecursion.hoplon.svg.make_svg_ctor("svg:font");
tailrecursion.hoplon.svg.font_face = tailrecursion.hoplon.svg.make_svg_ctor("svg:font-face");
tailrecursion.hoplon.svg.font_face_format = tailrecursion.hoplon.svg.make_svg_ctor("svg:font-face-format");
tailrecursion.hoplon.svg.font_face_name = tailrecursion.hoplon.svg.make_svg_ctor("svg:font-face-name");
tailrecursion.hoplon.svg.font_face_src = tailrecursion.hoplon.svg.make_svg_ctor("svg:font-face-src");
tailrecursion.hoplon.svg.font_face_uri = tailrecursion.hoplon.svg.make_svg_ctor("svg:font-face-uri");
tailrecursion.hoplon.svg.foreignObject = tailrecursion.hoplon.svg.make_svg_ctor("svg:foreignObject");
tailrecursion.hoplon.svg.g = tailrecursion.hoplon.svg.make_svg_ctor("svg:g");
tailrecursion.hoplon.svg.glyph = tailrecursion.hoplon.svg.make_svg_ctor("svg:glyph");
tailrecursion.hoplon.svg.glyphRef = tailrecursion.hoplon.svg.make_svg_ctor("svg:glyphRef");
tailrecursion.hoplon.svg.hkern = tailrecursion.hoplon.svg.make_svg_ctor("svg:hkern");
tailrecursion.hoplon.svg.image = tailrecursion.hoplon.svg.make_svg_ctor("svg:image");
tailrecursion.hoplon.svg.line = tailrecursion.hoplon.svg.make_svg_ctor("svg:line");
tailrecursion.hoplon.svg.linearGradient = tailrecursion.hoplon.svg.make_svg_ctor("svg:linearGradient");
tailrecursion.hoplon.svg.marker = tailrecursion.hoplon.svg.make_svg_ctor("svg:marker");
tailrecursion.hoplon.svg.mask = tailrecursion.hoplon.svg.make_svg_ctor("svg:mask");
tailrecursion.hoplon.svg.metadata = tailrecursion.hoplon.svg.make_svg_ctor("svg:metadata");
tailrecursion.hoplon.svg.missing_glyph = tailrecursion.hoplon.svg.make_svg_ctor("svg:missing-glyph");
tailrecursion.hoplon.svg.mpath = tailrecursion.hoplon.svg.make_svg_ctor("svg:mpath");
tailrecursion.hoplon.svg.path = tailrecursion.hoplon.svg.make_svg_ctor("svg:path");
tailrecursion.hoplon.svg.pattern = tailrecursion.hoplon.svg.make_svg_ctor("svg:pattern");
tailrecursion.hoplon.svg.polygon = tailrecursion.hoplon.svg.make_svg_ctor("svg:polygon");
tailrecursion.hoplon.svg.polyline = tailrecursion.hoplon.svg.make_svg_ctor("svg:polyline");
tailrecursion.hoplon.svg.radialGradient = tailrecursion.hoplon.svg.make_svg_ctor("svg:radialGradient");
tailrecursion.hoplon.svg.rect = tailrecursion.hoplon.svg.make_svg_ctor("svg:rect");
tailrecursion.hoplon.svg.script = tailrecursion.hoplon.svg.make_svg_ctor("svg:script");
tailrecursion.hoplon.svg.set = tailrecursion.hoplon.svg.make_svg_ctor("svg:set");
tailrecursion.hoplon.svg.stop = tailrecursion.hoplon.svg.make_svg_ctor("svg:stop");
tailrecursion.hoplon.svg.style = tailrecursion.hoplon.svg.make_svg_ctor("svg:style");
tailrecursion.hoplon.svg.svg = tailrecursion.hoplon.svg.make_svg_ctor("svg:svg");
tailrecursion.hoplon.svg.switch$ = tailrecursion.hoplon.svg.make_svg_ctor("svg:switch");
tailrecursion.hoplon.svg.symbol = tailrecursion.hoplon.svg.make_svg_ctor("svg:symbol");
tailrecursion.hoplon.svg.text = tailrecursion.hoplon.svg.make_svg_ctor("svg:text");
tailrecursion.hoplon.svg.textPath = tailrecursion.hoplon.svg.make_svg_ctor("svg:textPath");
tailrecursion.hoplon.svg.title = tailrecursion.hoplon.svg.make_svg_ctor("svg:title");
tailrecursion.hoplon.svg.tref = tailrecursion.hoplon.svg.make_svg_ctor("svg:tref");
tailrecursion.hoplon.svg.tspan = tailrecursion.hoplon.svg.make_svg_ctor("svg:tspan");
tailrecursion.hoplon.svg.use = tailrecursion.hoplon.svg.make_svg_ctor("svg:use");
tailrecursion.hoplon.svg.view = tailrecursion.hoplon.svg.make_svg_ctor("svg:view");
tailrecursion.hoplon.svg.vkern = tailrecursion.hoplon.svg.make_svg_ctor("svg:vkern");
