#!/usr/bin/env bash

rm -rf .gh-pages
mkdir .gh-pages

find . -maxdepth 1 -type d \! -iname ".*" \! -iname "deps" \
    | sed 's/^..//' \
    | while read a; do
        echo -e "\e[31mBuilding $a\e[0m"
        (cd "$a"; boot production; cp -R resources/public ../.gh-pages/"$a")
    done
