#!/usr/bin/env bash

rm -rf .gh-pages
mkdir .gh-pages

find . -maxdepth 1 -type d \! -iname ".*" \! -iname "deps" \
    | sed 's/^..//' \
    | while read a; do
        if [ -e "$a"/.no-demo ]; then continue; fi
        echo -e "\e[31mBuilding $a\e[0m"
        (cd "$a"; rm -rf public/js; rm -rf public/cljs-runtime; npm install; npx shadow-cljs release app; cp -R public ../.gh-pages/"$a")
    done
