// Compiled by ClojureScript 0.0-2227
goog.provide('tailrecursion.hoplon.app_pages._index_DOT_html');
goog.require('cljs.core');
goog.require('tailrecursion.javelin');
goog.require('tailrecursion.hoplon');
goog.require('tailrecursion.hoplon');
goog.require('tailrecursion.javelin');
tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit = (function hoploninit(){tailrecursion.hoplon.app_pages._index_DOT_html.form_name = tailrecursion.javelin.cell(null);
tailrecursion.hoplon.app_pages._index_DOT_html.form_email = tailrecursion.javelin.cell(null);
tailrecursion.hoplon.app_pages._index_DOT_html.validate_presence = (function validate_presence(v){return cljs.core.seq(v);
});
tailrecursion.hoplon.app_pages._index_DOT_html.validate_regexp = (function validate_regexp(r){return (function (v){return cljs.core.re_matches(r,(function (){var or__7267__auto__ = v;if(cljs.core.truth_(or__7267__auto__))
{return or__7267__auto__;
} else
{return "";
}
})());
});
});
tailrecursion.hoplon.app_pages._index_DOT_html.form_name_valid_QMARK_ = tailrecursion.javelin.lift((function (G__9407,G__9406){return new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$38,(cljs.core.truth_((G__9406.cljs$core$IFn$_invoke$arity$1 ? G__9406.cljs$core$IFn$_invoke$arity$1(G__9407) : G__9406.call(null,G__9407)))?true:false),cljs.core.constant$keyword$11,G__9407], null);
})).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.form_name,tailrecursion.hoplon.app_pages._index_DOT_html.validate_presence);
tailrecursion.hoplon.app_pages._index_DOT_html.form_email_valid_QMARK_ = tailrecursion.javelin.lift((function (G__9408,G__9409){return new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$38,(cljs.core.truth_((G__9408.cljs$core$IFn$_invoke$arity$1 ? G__9408.cljs$core$IFn$_invoke$arity$1(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i) : G__9408.call(null,/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i)).call(null,G__9409))?true:false),cljs.core.constant$keyword$11,G__9409], null);
})).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.validate_regexp,tailrecursion.hoplon.app_pages._index_DOT_html.form_email);
tailrecursion.hoplon.app_pages._index_DOT_html.is_form_valid_QMARK_ = tailrecursion.javelin.lift((function (G__9411,G__9410){var and__7255__auto__ = cljs.core.constant$keyword$38.cljs$core$IFn$_invoke$arity$1(G__9410);if(cljs.core.truth_(and__7255__auto__))
{return cljs.core.constant$keyword$38.cljs$core$IFn$_invoke$arity$1(G__9411);
} else
{return and__7255__auto__;
}
})).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.form_email_valid_QMARK_,tailrecursion.hoplon.app_pages._index_DOT_html.form_name_valid_QMARK_);
tailrecursion.hoplon.app_pages._index_DOT_html.form_data = tailrecursion.javelin.lift((function (G__9412,G__9413){return new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$39,G__9412,cljs.core.constant$keyword$40,G__9413], null);
})).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.form_name,tailrecursion.hoplon.app_pages._index_DOT_html.form_email);
tailrecursion.hoplon.app_pages._index_DOT_html.submit_form = (function submit_form(_){return alert(("Send: "+cljs.core.str.cljs$core$IFn$_invoke$arity$1(cljs.core.pr_str.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.deref(tailrecursion.hoplon.app_pages._index_DOT_html.form_data)], 0)))));
});
/**
* @param {...*} var_args
*/
tailrecursion.hoplon.app_pages._index_DOT_html.cell_input = (function() { 
var cell_input__delegate = function (args__8306__auto__){var vec__9416 = tailrecursion.hoplon.parse_args(args__8306__auto__);var map__9417 = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9416,0,null);var map__9417__$1 = ((cljs.core.seq_QMARK_(map__9417))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9417):map__9417);var attrs = map__9417__$1;var cell = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9417__$1,cljs.core.constant$keyword$41);var target_value = ((function (vec__9416,map__9417,map__9417__$1,attrs,cell){
return (function (p1__5373_SHARP_){return (tailrecursion.hoplon.do_BANG_.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.do_BANG_.cljs$core$IFn$_invoke$arity$2(p1__5373_SHARP_.currentTarget,cljs.core.constant$keyword$11) : tailrecursion.hoplon.do_BANG_.call(null,p1__5373_SHARP_.currentTarget,cljs.core.constant$keyword$11));
});})(vec__9416,map__9417,map__9417__$1,attrs,cell))
;return (tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.input.cljs$core$IFn$_invoke$arity$1(cljs.core.assoc.cljs$core$IFn$_invoke$arity$variadic(cljs.core.dissoc.cljs$core$IFn$_invoke$arity$2(attrs,cljs.core.constant$keyword$41),cljs.core.constant$keyword$42,cljs.core.constant$keyword$42.cljs$core$IFn$_invoke$arity$2(attrs,"text"),cljs.core.array_seq([cljs.core.constant$keyword$11,cell,cljs.core.constant$keyword$43,((function (target_value,vec__9416,map__9417,map__9417__$1,attrs,cell){
return (function (p1__5374_SHARP_){return cljs.core.reset_BANG_(cell,target_value(p1__5374_SHARP_));
});})(target_value,vec__9416,map__9417,map__9417__$1,attrs,cell))
], 0))) : tailrecursion.hoplon.input.call(null,cljs.core.assoc.cljs$core$IFn$_invoke$arity$variadic(cljs.core.dissoc.cljs$core$IFn$_invoke$arity$2(attrs,cljs.core.constant$keyword$41),cljs.core.constant$keyword$42,cljs.core.constant$keyword$42.cljs$core$IFn$_invoke$arity$2(attrs,"text"),cljs.core.array_seq([cljs.core.constant$keyword$11,cell,cljs.core.constant$keyword$43,((function (target_value,vec__9416,map__9417,map__9417__$1,attrs,cell){
return (function (p1__5374_SHARP_){return cljs.core.reset_BANG_(cell,target_value(p1__5374_SHARP_));
});})(target_value,vec__9416,map__9417,map__9417__$1,attrs,cell))
], 0))));
};
var cell_input = function (var_args){
var args__8306__auto__ = null;if (arguments.length > 0) {
  args__8306__auto__ = cljs.core.array_seq(Array.prototype.slice.call(arguments, 0),0);} 
return cell_input__delegate.call(this,args__8306__auto__);};
cell_input.cljs$lang$maxFixedArity = 0;
cell_input.cljs$lang$applyTo = (function (arglist__9445){
var args__8306__auto__ = cljs.core.seq(arglist__9445);
return cell_input__delegate(args__8306__auto__);
});
cell_input.cljs$core$IFn$_invoke$arity$variadic = cell_input__delegate;
return cell_input;
})()
;
/**
* @param {...*} var_args
*/
tailrecursion.hoplon.app_pages._index_DOT_html.form_group = (function() { 
var form_group__delegate = function (args__8306__auto__){var vec__9423 = tailrecursion.hoplon.parse_args(args__8306__auto__);var map__9424 = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9423,0,null);var map__9424__$1 = ((cljs.core.seq_QMARK_(map__9424))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__9424):map__9424);var attrs = map__9424__$1;var valid_QMARK_ = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__9424__$1,cljs.core.constant$keyword$38);var body = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9423,1,null);var dirty_QMARK_ = ((function (vec__9423,map__9424,map__9424__$1,attrs,valid_QMARK_,body){
return (function (v){return !((v == null));
});})(vec__9423,map__9424,map__9424__$1,attrs,valid_QMARK_,body))
;return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$2(cljs.core.dissoc.cljs$core$IFn$_invoke$arity$2(attrs,cljs.core.constant$keyword$38),body) : tailrecursion.hoplon.div.call(null,cljs.core.dissoc.cljs$core$IFn$_invoke$arity$2(attrs,cljs.core.constant$keyword$38),body)).call(null,cljs.core.constant$keyword$44,tailrecursion.javelin.lift(((function (dirty_QMARK_,vec__9423,map__9424,map__9424__$1,attrs,valid_QMARK_,body){
return (function (G__9425,G__9426,G__9427){return new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$45,true,cljs.core.constant$keyword$46,((G__9425.cljs$core$IFn$_invoke$arity$1 ? G__9425.cljs$core$IFn$_invoke$arity$1(cljs.core.constant$keyword$11.cljs$core$IFn$_invoke$arity$1(G__9426)) : G__9425.call(null,cljs.core.constant$keyword$11.cljs$core$IFn$_invoke$arity$1(G__9426)))) && ((G__9427.cljs$core$IFn$_invoke$arity$1 ? G__9427.cljs$core$IFn$_invoke$arity$1(cljs.core.constant$keyword$38.cljs$core$IFn$_invoke$arity$1(G__9426)) : G__9427.call(null,cljs.core.constant$keyword$38.cljs$core$IFn$_invoke$arity$1(G__9426))))], null);
});})(dirty_QMARK_,vec__9423,map__9424,map__9424__$1,attrs,valid_QMARK_,body))
).call(null,dirty_QMARK_,valid_QMARK_,cljs.core.not));
};
var form_group = function (var_args){
var args__8306__auto__ = null;if (arguments.length > 0) {
  args__8306__auto__ = cljs.core.array_seq(Array.prototype.slice.call(arguments, 0),0);} 
return form_group__delegate.call(this,args__8306__auto__);};
form_group.cljs$lang$maxFixedArity = 0;
form_group.cljs$lang$applyTo = (function (arglist__9446){
var args__8306__auto__ = cljs.core.seq(arglist__9446);
return form_group__delegate(args__8306__auto__);
});
form_group.cljs$core$IFn$_invoke$arity$variadic = form_group__delegate;
return form_group;
})()
;
/**
* @param {...*} var_args
*/
tailrecursion.hoplon.app_pages._index_DOT_html.input_control = (function() { 
var input_control__delegate = function (args__8306__auto__){var vec__9429 = tailrecursion.hoplon.parse_args(args__8306__auto__);var attrs = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__9429,0,null);return tailrecursion.hoplon.app_pages._index_DOT_html.cell_input.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([attrs], 0)).call(null,cljs.core.constant$keyword$44,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$47,true], null));
};
var input_control = function (var_args){
var args__8306__auto__ = null;if (arguments.length > 0) {
  args__8306__auto__ = cljs.core.array_seq(Array.prototype.slice.call(arguments, 0),0);} 
return input_control__delegate.call(this,args__8306__auto__);};
input_control.cljs$lang$maxFixedArity = 0;
input_control.cljs$lang$applyTo = (function (arglist__9447){
var args__8306__auto__ = cljs.core.seq(arglist__9447);
return input_control__delegate(args__8306__auto__);
});
input_control.cljs$core$IFn$_invoke$arity$variadic = input_control__delegate;
return input_control;
})()
;
(tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$2((tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$49,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$49,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Validated Form") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Validated Form")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"style.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"style.css"))], null);
})()) : tailrecursion.hoplon.html_head.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$49,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$49,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Validated Form") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Validated Form")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"style.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"style.css"))], null);
})())),(tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9436 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1("Name") : tailrecursion.hoplon.label.call(null,"Name"));var G__9437 = tailrecursion.hoplon.app_pages._index_DOT_html.input_control.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$41,tailrecursion.hoplon.app_pages._index_DOT_html.form_name], 0));var G__9435 = tailrecursion.hoplon.app_pages._index_DOT_html.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$38,tailrecursion.hoplon.app_pages._index_DOT_html.form_name_valid_QMARK_,G__9436,G__9437], 0));var G__9439 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1("Email") : tailrecursion.hoplon.label.call(null,"Email"));var G__9440 = tailrecursion.hoplon.app_pages._index_DOT_html.input_control.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$41,tailrecursion.hoplon.app_pages._index_DOT_html.form_email], 0));var G__9438 = tailrecursion.hoplon.app_pages._index_DOT_html.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$38,tailrecursion.hoplon.app_pages._index_DOT_html.form_email_valid_QMARK_,G__9439,G__9440], 0));var G__9442 = (tailrecursion.hoplon.button.cljs$core$IFn$_invoke$arity$7 ? tailrecursion.hoplon.button.cljs$core$IFn$_invoke$arity$7(cljs.core.constant$keyword$25,"btn btn-primary",cljs.core.constant$keyword$42,"submit",cljs.core.constant$keyword$50,tailrecursion.javelin.lift(((function (G__9436,G__9437,G__9435,G__9439,G__9440,G__9438){
return (function (G__9444,G__9443){return (G__9443.cljs$core$IFn$_invoke$arity$1 ? G__9443.cljs$core$IFn$_invoke$arity$1(G__9444) : G__9443.call(null,G__9444));
});})(G__9436,G__9437,G__9435,G__9439,G__9440,G__9438))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.is_form_valid_QMARK_,cljs.core.not),"Submit") : tailrecursion.hoplon.button.call(null,cljs.core.constant$keyword$25,"btn btn-primary",cljs.core.constant$keyword$42,"submit",cljs.core.constant$keyword$50,tailrecursion.javelin.lift(((function (G__9436,G__9437,G__9435,G__9439,G__9440,G__9438){
return (function (G__9444,G__9443){return (G__9443.cljs$core$IFn$_invoke$arity$1 ? G__9443.cljs$core$IFn$_invoke$arity$1(G__9444) : G__9443.call(null,G__9444));
});})(G__9436,G__9437,G__9435,G__9439,G__9440,G__9438))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.is_form_valid_QMARK_,cljs.core.not),"Submit"));var G__9441 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"text-right",G__9442) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"text-right",G__9442));var G__9434 = (tailrecursion.hoplon.form.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.form.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$51,tailrecursion.hoplon.app_pages._index_DOT_html.submit_form,G__9435,G__9438,G__9441) : tailrecursion.hoplon.form.call(null,cljs.core.constant$keyword$51,tailrecursion.hoplon.app_pages._index_DOT_html.submit_form,G__9435,G__9438,G__9441));var G__9433 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"inner cover",G__9434) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"inner cover",G__9434));var G__9432 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"cover-container",G__9433) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"cover-container",G__9433));var G__9431 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"site-wrapper-inner",G__9432) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"site-wrapper-inner",G__9432));var G__9430 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"site-wrapper",G__9431) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"site-wrapper",G__9431));return G__9430;
})()) : tailrecursion.hoplon.html_body.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9436 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1("Name") : tailrecursion.hoplon.label.call(null,"Name"));var G__9437 = tailrecursion.hoplon.app_pages._index_DOT_html.input_control.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$41,tailrecursion.hoplon.app_pages._index_DOT_html.form_name], 0));var G__9435 = tailrecursion.hoplon.app_pages._index_DOT_html.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$38,tailrecursion.hoplon.app_pages._index_DOT_html.form_name_valid_QMARK_,G__9436,G__9437], 0));var G__9439 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1("Email") : tailrecursion.hoplon.label.call(null,"Email"));var G__9440 = tailrecursion.hoplon.app_pages._index_DOT_html.input_control.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$41,tailrecursion.hoplon.app_pages._index_DOT_html.form_email], 0));var G__9438 = tailrecursion.hoplon.app_pages._index_DOT_html.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$38,tailrecursion.hoplon.app_pages._index_DOT_html.form_email_valid_QMARK_,G__9439,G__9440], 0));var G__9442 = (tailrecursion.hoplon.button.cljs$core$IFn$_invoke$arity$7 ? tailrecursion.hoplon.button.cljs$core$IFn$_invoke$arity$7(cljs.core.constant$keyword$25,"btn btn-primary",cljs.core.constant$keyword$42,"submit",cljs.core.constant$keyword$50,tailrecursion.javelin.lift(((function (G__9436,G__9437,G__9435,G__9439,G__9440,G__9438){
return (function (G__9444,G__9443){return (G__9443.cljs$core$IFn$_invoke$arity$1 ? G__9443.cljs$core$IFn$_invoke$arity$1(G__9444) : G__9443.call(null,G__9444));
});})(G__9436,G__9437,G__9435,G__9439,G__9440,G__9438))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.is_form_valid_QMARK_,cljs.core.not),"Submit") : tailrecursion.hoplon.button.call(null,cljs.core.constant$keyword$25,"btn btn-primary",cljs.core.constant$keyword$42,"submit",cljs.core.constant$keyword$50,tailrecursion.javelin.lift(((function (G__9436,G__9437,G__9435,G__9439,G__9440,G__9438){
return (function (G__9444,G__9443){return (G__9443.cljs$core$IFn$_invoke$arity$1 ? G__9443.cljs$core$IFn$_invoke$arity$1(G__9444) : G__9443.call(null,G__9444));
});})(G__9436,G__9437,G__9435,G__9439,G__9440,G__9438))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.is_form_valid_QMARK_,cljs.core.not),"Submit"));var G__9441 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"text-right",G__9442) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"text-right",G__9442));var G__9434 = (tailrecursion.hoplon.form.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.form.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$51,tailrecursion.hoplon.app_pages._index_DOT_html.submit_form,G__9435,G__9438,G__9441) : tailrecursion.hoplon.form.call(null,cljs.core.constant$keyword$51,tailrecursion.hoplon.app_pages._index_DOT_html.submit_form,G__9435,G__9438,G__9441));var G__9433 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"inner cover",G__9434) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"inner cover",G__9434));var G__9432 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"cover-container",G__9433) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"cover-container",G__9433));var G__9431 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"site-wrapper-inner",G__9432) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"site-wrapper-inner",G__9432));var G__9430 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"site-wrapper",G__9431) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"site-wrapper",G__9431));return G__9430;
})()))) : tailrecursion.hoplon.html.call(null,(tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$49,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$49,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Validated Form") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Validated Form")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"style.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"style.css"))], null);
})()) : tailrecursion.hoplon.html_head.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 5, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$49,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$42,"text/css",cljs.core.constant$keyword$49,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Validated Form") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Validated Form")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css")),(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"style.css") : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$48,"stylesheet",cljs.core.constant$keyword$49,"style.css"))], null);
})())),(tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9436 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1("Name") : tailrecursion.hoplon.label.call(null,"Name"));var G__9437 = tailrecursion.hoplon.app_pages._index_DOT_html.input_control.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$41,tailrecursion.hoplon.app_pages._index_DOT_html.form_name], 0));var G__9435 = tailrecursion.hoplon.app_pages._index_DOT_html.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$38,tailrecursion.hoplon.app_pages._index_DOT_html.form_name_valid_QMARK_,G__9436,G__9437], 0));var G__9439 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1("Email") : tailrecursion.hoplon.label.call(null,"Email"));var G__9440 = tailrecursion.hoplon.app_pages._index_DOT_html.input_control.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$41,tailrecursion.hoplon.app_pages._index_DOT_html.form_email], 0));var G__9438 = tailrecursion.hoplon.app_pages._index_DOT_html.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$38,tailrecursion.hoplon.app_pages._index_DOT_html.form_email_valid_QMARK_,G__9439,G__9440], 0));var G__9442 = (tailrecursion.hoplon.button.cljs$core$IFn$_invoke$arity$7 ? tailrecursion.hoplon.button.cljs$core$IFn$_invoke$arity$7(cljs.core.constant$keyword$25,"btn btn-primary",cljs.core.constant$keyword$42,"submit",cljs.core.constant$keyword$50,tailrecursion.javelin.lift(((function (G__9436,G__9437,G__9435,G__9439,G__9440,G__9438){
return (function (G__9444,G__9443){return (G__9443.cljs$core$IFn$_invoke$arity$1 ? G__9443.cljs$core$IFn$_invoke$arity$1(G__9444) : G__9443.call(null,G__9444));
});})(G__9436,G__9437,G__9435,G__9439,G__9440,G__9438))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.is_form_valid_QMARK_,cljs.core.not),"Submit") : tailrecursion.hoplon.button.call(null,cljs.core.constant$keyword$25,"btn btn-primary",cljs.core.constant$keyword$42,"submit",cljs.core.constant$keyword$50,tailrecursion.javelin.lift(((function (G__9436,G__9437,G__9435,G__9439,G__9440,G__9438){
return (function (G__9444,G__9443){return (G__9443.cljs$core$IFn$_invoke$arity$1 ? G__9443.cljs$core$IFn$_invoke$arity$1(G__9444) : G__9443.call(null,G__9444));
});})(G__9436,G__9437,G__9435,G__9439,G__9440,G__9438))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.is_form_valid_QMARK_,cljs.core.not),"Submit"));var G__9441 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"text-right",G__9442) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"text-right",G__9442));var G__9434 = (tailrecursion.hoplon.form.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.form.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$51,tailrecursion.hoplon.app_pages._index_DOT_html.submit_form,G__9435,G__9438,G__9441) : tailrecursion.hoplon.form.call(null,cljs.core.constant$keyword$51,tailrecursion.hoplon.app_pages._index_DOT_html.submit_form,G__9435,G__9438,G__9441));var G__9433 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"inner cover",G__9434) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"inner cover",G__9434));var G__9432 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"cover-container",G__9433) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"cover-container",G__9433));var G__9431 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"site-wrapper-inner",G__9432) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"site-wrapper-inner",G__9432));var G__9430 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"site-wrapper",G__9431) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"site-wrapper",G__9431));return G__9430;
})()) : tailrecursion.hoplon.html_body.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var G__9436 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1("Name") : tailrecursion.hoplon.label.call(null,"Name"));var G__9437 = tailrecursion.hoplon.app_pages._index_DOT_html.input_control.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$41,tailrecursion.hoplon.app_pages._index_DOT_html.form_name], 0));var G__9435 = tailrecursion.hoplon.app_pages._index_DOT_html.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$38,tailrecursion.hoplon.app_pages._index_DOT_html.form_name_valid_QMARK_,G__9436,G__9437], 0));var G__9439 = (tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.label.cljs$core$IFn$_invoke$arity$1("Email") : tailrecursion.hoplon.label.call(null,"Email"));var G__9440 = tailrecursion.hoplon.app_pages._index_DOT_html.input_control.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$41,tailrecursion.hoplon.app_pages._index_DOT_html.form_email], 0));var G__9438 = tailrecursion.hoplon.app_pages._index_DOT_html.form_group.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$38,tailrecursion.hoplon.app_pages._index_DOT_html.form_email_valid_QMARK_,G__9439,G__9440], 0));var G__9442 = (tailrecursion.hoplon.button.cljs$core$IFn$_invoke$arity$7 ? tailrecursion.hoplon.button.cljs$core$IFn$_invoke$arity$7(cljs.core.constant$keyword$25,"btn btn-primary",cljs.core.constant$keyword$42,"submit",cljs.core.constant$keyword$50,tailrecursion.javelin.lift(((function (G__9436,G__9437,G__9435,G__9439,G__9440,G__9438){
return (function (G__9444,G__9443){return (G__9443.cljs$core$IFn$_invoke$arity$1 ? G__9443.cljs$core$IFn$_invoke$arity$1(G__9444) : G__9443.call(null,G__9444));
});})(G__9436,G__9437,G__9435,G__9439,G__9440,G__9438))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.is_form_valid_QMARK_,cljs.core.not),"Submit") : tailrecursion.hoplon.button.call(null,cljs.core.constant$keyword$25,"btn btn-primary",cljs.core.constant$keyword$42,"submit",cljs.core.constant$keyword$50,tailrecursion.javelin.lift(((function (G__9436,G__9437,G__9435,G__9439,G__9440,G__9438){
return (function (G__9444,G__9443){return (G__9443.cljs$core$IFn$_invoke$arity$1 ? G__9443.cljs$core$IFn$_invoke$arity$1(G__9444) : G__9443.call(null,G__9444));
});})(G__9436,G__9437,G__9435,G__9439,G__9440,G__9438))
).call(null,tailrecursion.hoplon.app_pages._index_DOT_html.is_form_valid_QMARK_,cljs.core.not),"Submit"));var G__9441 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"text-right",G__9442) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"text-right",G__9442));var G__9434 = (tailrecursion.hoplon.form.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.form.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$51,tailrecursion.hoplon.app_pages._index_DOT_html.submit_form,G__9435,G__9438,G__9441) : tailrecursion.hoplon.form.call(null,cljs.core.constant$keyword$51,tailrecursion.hoplon.app_pages._index_DOT_html.submit_form,G__9435,G__9438,G__9441));var G__9433 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"inner cover",G__9434) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"inner cover",G__9434));var G__9432 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"cover-container",G__9433) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"cover-container",G__9433));var G__9431 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"site-wrapper-inner",G__9432) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"site-wrapper-inner",G__9432));var G__9430 = (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$25,"site-wrapper",G__9431) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$25,"site-wrapper",G__9431));return G__9430;
})()))));
return tailrecursion.hoplon.init();
});
goog.exportSymbol('tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit', tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit);
