// Compiled by ClojureScript 0.0-2227
goog.provide('tailrecursion.hoplon.app_pages._index_DOT_html');
goog.require('cljs.core');
goog.require('hoplon.twitter.bootstrap');
goog.require('hoplon.google.api');
goog.require('tailrecursion.javelin');
goog.require('tailrecursion.hoplon');
goog.require('tailrecursion.hoplon');
goog.require('tailrecursion.javelin');
goog.require('hoplon.twitter.bootstrap');
goog.require('hoplon.twitter.bootstrap');
goog.require('hoplon.google.api');
goog.require('hoplon.google.api');
tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit = (function hoploninit(){cljs.core.reset_BANG_(hoplon.google.api.api_key,"AIzaSyA3SuTQQlfhLL0O--JS91QqUkKBJp6HE7g");
tailrecursion.hoplon.app_pages._index_DOT_html.miami_beach = new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$59,"Miami Beach",cljs.core.constant$keyword$74,25.813,cljs.core.constant$keyword$73,-80.1341], null);
tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco = new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$59,"San Francisco",cljs.core.constant$keyword$74,37.7833,cljs.core.constant$keyword$73,-122.4167], null);
/**
* @param {...*} var_args
*/
tailrecursion.hoplon.app_pages._index_DOT_html.info = (function() { 
var info__delegate = function (args__8680__auto__){var vec__10006 = tailrecursion.hoplon.parse_args(args__8680__auto__);var map__10007 = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__10006,0,null);var map__10007__$1 = ((cljs.core.seq_QMARK_(map__10007))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__10007):map__10007);var body = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__10007__$1,cljs.core.constant$keyword$78);var title = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__10007__$1,cljs.core.constant$keyword$79);var _ = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__10006,1,null);return (tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5 ? tailrecursion.hoplon.div.cljs$core$IFn$_invoke$arity$5(cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$80,"100px",cljs.core.constant$keyword$81,"300px"], null),(tailrecursion.hoplon.h4.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h4.cljs$core$IFn$_invoke$arity$1(title) : tailrecursion.hoplon.h4.call(null,title)),(tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null)),(tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1(body) : tailrecursion.hoplon.p.call(null,body))) : tailrecursion.hoplon.div.call(null,cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$80,"100px",cljs.core.constant$keyword$81,"300px"], null),(tailrecursion.hoplon.h4.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h4.cljs$core$IFn$_invoke$arity$1(title) : tailrecursion.hoplon.h4.call(null,title)),(tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null)),(tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$1(body) : tailrecursion.hoplon.p.call(null,body))));
};
var info = function (var_args){
var args__8680__auto__ = null;if (arguments.length > 0) {
  args__8680__auto__ = cljs.core.array_seq(Array.prototype.slice.call(arguments, 0),0);} 
return info__delegate.call(this,args__8680__auto__);};
info.cljs$lang$maxFixedArity = 0;
info.cljs$lang$applyTo = (function (arglist__10028){
var args__8680__auto__ = cljs.core.seq(arglist__10028);
return info__delegate(args__8680__auto__);
});
info.cljs$core$IFn$_invoke$arity$variadic = info__delegate;
return info;
})()
;
tailrecursion.hoplon.app_pages._index_DOT_html.rand_pin = (function rand_pin(p__10008){var map__10011 = p__10008;var map__10011__$1 = ((cljs.core.seq_QMARK_(map__10011))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__10011):map__10011);var lon = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__10011__$1,cljs.core.constant$keyword$73);var lat = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__10011__$1,cljs.core.constant$keyword$74);var name = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__10011__$1,cljs.core.constant$keyword$59);var perturb_BANG_ = ((function (map__10011,map__10011__$1,lon,lat,name){
return (function (p1__6746_SHARP_){return (p1__6746_SHARP_ + (0.03 * (cljs.core.rand.cljs$core$IFn$_invoke$arity$0() - 0.5))).toFixed(4);
});})(map__10011,map__10011__$1,lon,lat,name))
;var vec__10012 = cljs.core.map.cljs$core$IFn$_invoke$arity$2(perturb_BANG_,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [lat,lon], null));var lat__$1 = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__10012,0,null);var lon__$1 = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__10012,1,null);var name__$1 = ("A place in "+cljs.core.str.cljs$core$IFn$_invoke$arity$1(name));var content = ("Coordinates: "+cljs.core.str.cljs$core$IFn$_invoke$arity$1(lat__$1)+"\u00BAN, "+cljs.core.str.cljs$core$IFn$_invoke$arity$1(lon__$1)+"\u00BAW.");return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$74,lat__$1,cljs.core.constant$keyword$73,lon__$1,cljs.core.constant$keyword$75,tailrecursion.hoplon.app_pages._index_DOT_html.info.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$79,name__$1,cljs.core.constant$keyword$78,content], 0))], null);
});
tailrecursion.hoplon.app_pages._index_DOT_html.rand_pins = (function rand_pins(city,n){return cljs.core.vec(cljs.core.take(n,cljs.core.repeatedly.cljs$core$IFn$_invoke$arity$1((function (){return tailrecursion.hoplon.app_pages._index_DOT_html.rand_pin(city);
}))));
});
tailrecursion.hoplon.app_pages._index_DOT_html.do_steps = (function do_steps(msec,p__10013){var vec__10015 = p__10013;var step = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__10015,0,null);var steps = cljs.core.nthnext(vec__10015,1);return setTimeout(((function (vec__10015,step,steps){
return (function (){if(cljs.core.truth_(step))
{(step.cljs$core$IFn$_invoke$arity$0 ? step.cljs$core$IFn$_invoke$arity$0() : step.call(null));
} else
{}
if(steps)
{return do_steps(msec,steps);
} else
{return null;
}
});})(vec__10015,step,steps))
,msec);
});
tailrecursion.hoplon.app_pages._index_DOT_html.bounce_marker = (function bounce_marker(marker){marker.setAnimation(google.maps.Animation.BOUNCE);
return setTimeout((function (){return marker.setAnimation(null);
}),1400);
});
tailrecursion.hoplon.app_pages._index_DOT_html.auto_QMARK_ = tailrecursion.javelin.cell(true);
tailrecursion.hoplon.app_pages._index_DOT_html.opts = tailrecursion.javelin.cell(new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$82,8], null));
tailrecursion.hoplon.app_pages._index_DOT_html.pins = tailrecursion.javelin.cell(tailrecursion.hoplon.app_pages._index_DOT_html.rand_pins(tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,4));
tailrecursion.hoplon.add_initfn_BANG_((function (){return setTimeout((function (){return tailrecursion.hoplon.app_pages._index_DOT_html.do_steps(1500,new cljs.core.PersistentVector(null, 11, 5, cljs.core.PersistentVector.EMPTY_NODE, [(function (){return cljs.core.reset_BANG_(tailrecursion.hoplon.app_pages._index_DOT_html.pins,tailrecursion.hoplon.app_pages._index_DOT_html.rand_pins(tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,4));
}),(function (){return cljs.core.reset_BANG_(tailrecursion.hoplon.app_pages._index_DOT_html.pins,tailrecursion.hoplon.app_pages._index_DOT_html.rand_pins(tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,4));
}),(function (){return cljs.core.reset_BANG_(tailrecursion.hoplon.app_pages._index_DOT_html.pins,tailrecursion.hoplon.app_pages._index_DOT_html.rand_pins(tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,4));
}),(function (){return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.auto_QMARK_,cljs.core.not);
}),(function (){return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.pop);
}),(function (){return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.pop);
}),(function (){return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$3(tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.conj,tailrecursion.hoplon.app_pages._index_DOT_html.rand_pin(tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco));
}),(function (){return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$3(tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.conj,tailrecursion.hoplon.app_pages._index_DOT_html.rand_pin(tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco));
}),(function (){return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$2(tailrecursion.hoplon.app_pages._index_DOT_html.auto_QMARK_,cljs.core.not);
}),(function (){return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$3(tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.into,tailrecursion.hoplon.app_pages._index_DOT_html.rand_pins(tailrecursion.hoplon.app_pages._index_DOT_html.miami_beach,5));
}),(function (){return cljs.core.swap_BANG_.cljs$core$IFn$_invoke$arity$3(tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.subvec,4);
})], null));
}),1000);
}));
(tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$4 ? tailrecursion.hoplon.html.cljs$core$IFn$_invoke$arity$4(cljs.core.constant$keyword$83,"en",(tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$38,"stylesheet",cljs.core.constant$keyword$39,"text/css",cljs.core.constant$keyword$40,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$38,"stylesheet",cljs.core.constant$keyword$39,"text/css",cljs.core.constant$keyword$40,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Google Maps") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Google Maps"))], null);
})()) : tailrecursion.hoplon.html_head.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$38,"stylesheet",cljs.core.constant$keyword$39,"text/css",cljs.core.constant$keyword$40,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$38,"stylesheet",cljs.core.constant$keyword$39,"text/css",cljs.core.constant$keyword$40,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Google Maps") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Google Maps"))], null);
})())),(tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var G__10017 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Hoplon & Google Maps") : tailrecursion.hoplon.h1.call(null,"Hoplon & Google Maps"));var G__10018 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__10021 = hoplon.google.api.google_map.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.constant$keyword$80,"600px",cljs.core.constant$keyword$81,"100%",cljs.core.constant$keyword$84,"0 auto",cljs.core.constant$keyword$85,"1px solid red"], null),cljs.core.constant$keyword$71,tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,cljs.core.constant$keyword$69,tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.constant$keyword$68,((function (G__10017,G__10018){
return (function (p1__6748_SHARP_,p2__6747_SHARP_){return tailrecursion.hoplon.app_pages._index_DOT_html.bounce_marker(p2__6747_SHARP_);
});})(G__10017,G__10018))
,cljs.core.constant$keyword$67,((function (G__10017,G__10018){
return (function (p1__6749_SHARP_){return cljs.core.print.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$86,p1__6749_SHARP_], 0));
});})(G__10017,G__10018))
,cljs.core.constant$keyword$66,tailrecursion.hoplon.app_pages._index_DOT_html.auto_QMARK_,cljs.core.constant$keyword$70,tailrecursion.hoplon.app_pages._index_DOT_html.opts], 0));var G__10020 = hoplon.twitter.bootstrap.tab.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$59,"First Map",G__10021], 0));var G__10025 = cljs.core.deref(tailrecursion.hoplon.app_pages._index_DOT_html.pins);var G__10023 = hoplon.google.api.google_map.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.constant$keyword$80,"600px",cljs.core.constant$keyword$81,"100%",cljs.core.constant$keyword$84,"0 auto",cljs.core.constant$keyword$85,"1px solid blue"], null),cljs.core.constant$keyword$71,tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,cljs.core.constant$keyword$69,G__10025,cljs.core.constant$keyword$70,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$82,12], null)], 0));var G__10022 = hoplon.twitter.bootstrap.tab.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$59,"Second Map",G__10023], 0));var G__10019 = hoplon.twitter.bootstrap.tabs.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__10020,G__10022], 0));var G__10024 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__10027 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$40,"https://github.com/tailrecursion/hoplon-demos/blob/master/google-maps/src/index.cljs.hl","source code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$40,"https://github.com/tailrecursion/hoplon-demos/blob/master/google-maps/src/index.cljs.hl","source code"));var G__10026 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$87,"center"], null),G__10027) : tailrecursion.hoplon.p.call(null,cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$87,"center"], null),G__10027));var G__10016 = hoplon.twitter.bootstrap.container.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__10017,G__10018,G__10019,G__10024,G__10026], 0));return G__10016;
})()) : tailrecursion.hoplon.html_body.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var G__10017 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Hoplon & Google Maps") : tailrecursion.hoplon.h1.call(null,"Hoplon & Google Maps"));var G__10018 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__10021 = hoplon.google.api.google_map.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.constant$keyword$80,"600px",cljs.core.constant$keyword$81,"100%",cljs.core.constant$keyword$84,"0 auto",cljs.core.constant$keyword$85,"1px solid red"], null),cljs.core.constant$keyword$71,tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,cljs.core.constant$keyword$69,tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.constant$keyword$68,((function (G__10017,G__10018){
return (function (p1__6748_SHARP_,p2__6747_SHARP_){return tailrecursion.hoplon.app_pages._index_DOT_html.bounce_marker(p2__6747_SHARP_);
});})(G__10017,G__10018))
,cljs.core.constant$keyword$67,((function (G__10017,G__10018){
return (function (p1__6749_SHARP_){return cljs.core.print.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$86,p1__6749_SHARP_], 0));
});})(G__10017,G__10018))
,cljs.core.constant$keyword$66,tailrecursion.hoplon.app_pages._index_DOT_html.auto_QMARK_,cljs.core.constant$keyword$70,tailrecursion.hoplon.app_pages._index_DOT_html.opts], 0));var G__10020 = hoplon.twitter.bootstrap.tab.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$59,"First Map",G__10021], 0));var G__10025 = cljs.core.deref(tailrecursion.hoplon.app_pages._index_DOT_html.pins);var G__10023 = hoplon.google.api.google_map.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.constant$keyword$80,"600px",cljs.core.constant$keyword$81,"100%",cljs.core.constant$keyword$84,"0 auto",cljs.core.constant$keyword$85,"1px solid blue"], null),cljs.core.constant$keyword$71,tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,cljs.core.constant$keyword$69,G__10025,cljs.core.constant$keyword$70,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$82,12], null)], 0));var G__10022 = hoplon.twitter.bootstrap.tab.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$59,"Second Map",G__10023], 0));var G__10019 = hoplon.twitter.bootstrap.tabs.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__10020,G__10022], 0));var G__10024 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__10027 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$40,"https://github.com/tailrecursion/hoplon-demos/blob/master/google-maps/src/index.cljs.hl","source code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$40,"https://github.com/tailrecursion/hoplon-demos/blob/master/google-maps/src/index.cljs.hl","source code"));var G__10026 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$87,"center"], null),G__10027) : tailrecursion.hoplon.p.call(null,cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$87,"center"], null),G__10027));var G__10016 = hoplon.twitter.bootstrap.container.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__10017,G__10018,G__10019,G__10024,G__10026], 0));return G__10016;
})()))) : tailrecursion.hoplon.html.call(null,cljs.core.constant$keyword$83,"en",(tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_head.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$38,"stylesheet",cljs.core.constant$keyword$39,"text/css",cljs.core.constant$keyword$40,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$38,"stylesheet",cljs.core.constant$keyword$39,"text/css",cljs.core.constant$keyword$40,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Google Maps") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Google Maps"))], null);
})()) : tailrecursion.hoplon.html_head.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var meta = tailrecursion.hoplon.html_meta;return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6 ? tailrecursion.hoplon.link.cljs$core$IFn$_invoke$arity$6(cljs.core.constant$keyword$38,"stylesheet",cljs.core.constant$keyword$39,"text/css",cljs.core.constant$keyword$40,(window["_hoplon_main_css"])) : tailrecursion.hoplon.link.call(null,cljs.core.constant$keyword$38,"stylesheet",cljs.core.constant$keyword$39,"text/css",cljs.core.constant$keyword$40,(window["_hoplon_main_css"]))),(tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.title.cljs$core$IFn$_invoke$arity$1("Hoplon \u2022 Google Maps") : tailrecursion.hoplon.title.call(null,"Hoplon \u2022 Google Maps"))], null);
})())),(tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2 ? tailrecursion.hoplon.html_body.cljs$core$IFn$_invoke$arity$2(cljs.core.PersistentArrayMap.EMPTY,(function (){var G__10017 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Hoplon & Google Maps") : tailrecursion.hoplon.h1.call(null,"Hoplon & Google Maps"));var G__10018 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__10021 = hoplon.google.api.google_map.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.constant$keyword$80,"600px",cljs.core.constant$keyword$81,"100%",cljs.core.constant$keyword$84,"0 auto",cljs.core.constant$keyword$85,"1px solid red"], null),cljs.core.constant$keyword$71,tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,cljs.core.constant$keyword$69,tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.constant$keyword$68,((function (G__10017,G__10018){
return (function (p1__6748_SHARP_,p2__6747_SHARP_){return tailrecursion.hoplon.app_pages._index_DOT_html.bounce_marker(p2__6747_SHARP_);
});})(G__10017,G__10018))
,cljs.core.constant$keyword$67,((function (G__10017,G__10018){
return (function (p1__6749_SHARP_){return cljs.core.print.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$86,p1__6749_SHARP_], 0));
});})(G__10017,G__10018))
,cljs.core.constant$keyword$66,tailrecursion.hoplon.app_pages._index_DOT_html.auto_QMARK_,cljs.core.constant$keyword$70,tailrecursion.hoplon.app_pages._index_DOT_html.opts], 0));var G__10020 = hoplon.twitter.bootstrap.tab.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$59,"First Map",G__10021], 0));var G__10025 = cljs.core.deref(tailrecursion.hoplon.app_pages._index_DOT_html.pins);var G__10023 = hoplon.google.api.google_map.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.constant$keyword$80,"600px",cljs.core.constant$keyword$81,"100%",cljs.core.constant$keyword$84,"0 auto",cljs.core.constant$keyword$85,"1px solid blue"], null),cljs.core.constant$keyword$71,tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,cljs.core.constant$keyword$69,G__10025,cljs.core.constant$keyword$70,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$82,12], null)], 0));var G__10022 = hoplon.twitter.bootstrap.tab.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$59,"Second Map",G__10023], 0));var G__10019 = hoplon.twitter.bootstrap.tabs.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__10020,G__10022], 0));var G__10024 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__10027 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$40,"https://github.com/tailrecursion/hoplon-demos/blob/master/google-maps/src/index.cljs.hl","source code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$40,"https://github.com/tailrecursion/hoplon-demos/blob/master/google-maps/src/index.cljs.hl","source code"));var G__10026 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$87,"center"], null),G__10027) : tailrecursion.hoplon.p.call(null,cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$87,"center"], null),G__10027));var G__10016 = hoplon.twitter.bootstrap.container.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__10017,G__10018,G__10019,G__10024,G__10026], 0));return G__10016;
})()) : tailrecursion.hoplon.html_body.call(null,cljs.core.PersistentArrayMap.EMPTY,(function (){var G__10017 = (tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1 ? tailrecursion.hoplon.h1.cljs$core$IFn$_invoke$arity$1("Hoplon & Google Maps") : tailrecursion.hoplon.h1.call(null,"Hoplon & Google Maps"));var G__10018 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__10021 = hoplon.google.api.google_map.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.constant$keyword$80,"600px",cljs.core.constant$keyword$81,"100%",cljs.core.constant$keyword$84,"0 auto",cljs.core.constant$keyword$85,"1px solid red"], null),cljs.core.constant$keyword$71,tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,cljs.core.constant$keyword$69,tailrecursion.hoplon.app_pages._index_DOT_html.pins,cljs.core.constant$keyword$68,((function (G__10017,G__10018){
return (function (p1__6748_SHARP_,p2__6747_SHARP_){return tailrecursion.hoplon.app_pages._index_DOT_html.bounce_marker(p2__6747_SHARP_);
});})(G__10017,G__10018))
,cljs.core.constant$keyword$67,((function (G__10017,G__10018){
return (function (p1__6749_SHARP_){return cljs.core.print.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$86,p1__6749_SHARP_], 0));
});})(G__10017,G__10018))
,cljs.core.constant$keyword$66,tailrecursion.hoplon.app_pages._index_DOT_html.auto_QMARK_,cljs.core.constant$keyword$70,tailrecursion.hoplon.app_pages._index_DOT_html.opts], 0));var G__10020 = hoplon.twitter.bootstrap.tab.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$59,"First Map",G__10021], 0));var G__10025 = cljs.core.deref(tailrecursion.hoplon.app_pages._index_DOT_html.pins);var G__10023 = hoplon.google.api.google_map.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.constant$keyword$80,"600px",cljs.core.constant$keyword$81,"100%",cljs.core.constant$keyword$84,"0 auto",cljs.core.constant$keyword$85,"1px solid blue"], null),cljs.core.constant$keyword$71,tailrecursion.hoplon.app_pages._index_DOT_html.san_francisco,cljs.core.constant$keyword$69,G__10025,cljs.core.constant$keyword$70,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$82,12], null)], 0));var G__10022 = hoplon.twitter.bootstrap.tab.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$59,"Second Map",G__10023], 0));var G__10019 = hoplon.twitter.bootstrap.tabs.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__10020,G__10022], 0));var G__10024 = (tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0 ? tailrecursion.hoplon.hr.cljs$core$IFn$_invoke$arity$0() : tailrecursion.hoplon.hr.call(null));var G__10027 = (tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.a.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$40,"https://github.com/tailrecursion/hoplon-demos/blob/master/google-maps/src/index.cljs.hl","source code") : tailrecursion.hoplon.a.call(null,cljs.core.constant$keyword$40,"https://github.com/tailrecursion/hoplon-demos/blob/master/google-maps/src/index.cljs.hl","source code"));var G__10026 = (tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3 ? tailrecursion.hoplon.p.cljs$core$IFn$_invoke$arity$3(cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$87,"center"], null),G__10027) : tailrecursion.hoplon.p.call(null,cljs.core.constant$keyword$26,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$87,"center"], null),G__10027));var G__10016 = hoplon.twitter.bootstrap.container.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([G__10017,G__10018,G__10019,G__10024,G__10026], 0));return G__10016;
})()))));
return tailrecursion.hoplon.init();
});
goog.exportSymbol('tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit', tailrecursion.hoplon.app_pages._index_DOT_html.hoploninit);
